[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# memory_limit = 43554432
 memory_limit = 80000000000000
# memory_limit = 33554432 # default limit
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
